name: Build and Run Tests

on:  [push]
    
permissions:
  id-token: write
  contents: read

jobs:
  build_and_test:
    uses: ./.github/workflows/build.yml
    with:
      save_dist: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}